version: "3"

services: #This section defines all the different containers we will create.
  covidpass: 
      command: dev #command to execute
      # restart: unless-stopped
      env_file: .env.local
      user: root
      volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
      depends_on:
        - "verifier"
        - "hitcounter"
      networks:
        - app-network

  verifier:
      build:
        context: ./submodules/VaxVerify #This specifies the location of our Dockerfile
        dockerfile: Dockerfile
      image: verifier:verifier
      env_file: ./submodules/VaxVerify/.env.local
      volumes:
        - ./submodules/VaxVerify:/usr/src/app
        - /usr/src/app/node_modules
        - /usr/src/app/functions/node_modules
      container_name: verifier
      ports: #This is used to map the container’s ports to the host machine.
        - "5003:5003"
        - "5001:5001"
        - "4000:4000"
        - "5002:5002"
      networks:
        - app-network

  hitcounter:
      build:
        context: ./submodules/hit-counter
        dockerfile: Dockerfile
      image: hitcounter:hitcounter
      volumes:
        - ./submodules/hit-counter:/usr/src/app
      container_name: hitcounter
      ports:
        - "8080:8080"
      networks:
        - app-network

  # covidpass:
  #     build:
  #       context: ./submodules/CovidPassApiNet #This specifies the location of our Dockerfile
  #       dockerfile: Dockerfile
  #     image: covidpass:covidpass
  #     volumes:
  #       - ./submodules/CovidPassApiNet:/usr/src/app
  #     container_name: covidpass
  #     ports: #This is used to map the container’s ports to the host machine.
  #       - "80:80"
  #     networks:
  #       - app-network

networks:
  app-network:
    driver: bridge